### ISSUE TITLE
Bootstrapping issue for Dashboard

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#153]
Event-driven creation of the dashboard is currently too late since `RootMailReady` triggers green after the DNS delegation is done.

**Comment by s0enke** [comment]
We could add a schedule for the generator Lambda as well? IIRC we decided against it in the first place to save costs / executions. Or maybe we find another good event trigger for the first time creation.

**Comment by sbstjn** [comment]
What about creating the CloudFormation stack for the dashboard before setting up the RootMail stuff?

```
RootMail:
  Type: AWS::CloudFormation::Stack
  DependsOn: LivingDocumentation
```

Of course, the lambda functions needs some minor tweaks for this to work without failures:

```python
rootmail_ready_alarm_state = cw.describe_alarms(
  AlarmNames=[
      'superwerker-RootMailReady',
  ]
)['MetricAlarms'][0]['StateValue']

if rootmail_ready_alarm_state == 'OK':
```

**Comment by s0enke** [comment]
> What about creating the CloudFormation stack for the dashboard before setting up the RootMail stuff?

This should be the case anyway since there is no CloudFormation dependency between the stacks, e.g.:

![image](https://user-images.githubusercontent.com/219372/110790795-c43a4300-8271-11eb-9ebc-88c65bd3258d.png)

So think we wouldn't need to depend on `rootmail` on `living-documentation.

My [idea](https://github.com/superwerker/superwerker/issues/153#issuecomment-781180088) was to trigger the dashboard generation Lambda once in the `living-documentation stack so the dashboard would appear as soon the `living-documentation is rolled out. Of course we would still need exception handling for the maybe not yet existing `superwerker-RootMailReady` CW Alarm.

**Comment by sbstjn** [comment]
So, maybe we just add a custom CF resource to use the SDK and invoke the lambda function? 🙈
