### ISSUE TITLE
Non default AWS region (eu-central-2) fails

### ISSUE THREAD

**Issue by c-a-m-a-c** [superwerker/superwerker#451]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version
[v.1.0.0](https://github.com/superwerker/superwerker/releases/tag/v1.0.0)

### Expected Behaviour

Successful deployment of superwerker CloudFormation (CFN) stack with CREATE_COMPLETE on a newly created AWS Account in eu-central-2.

(Initially I ran an EC2 instance in order to prevent issues with the internal trust score of the newly created AWS Account.)

### Actual Behaviour

superwerker CFN stack cannot be deployed successfully. The following nested stacks fail to create:
1. superwerker-Budget-REACTED (Budget) with reason: "Template format error: Unrecognized resource types: [AWS::Budgets::Budget]"
2. superwerker-ControlTower-REDACTED (ControlTower) with reason: "The following resource(s) failed to create: [LandingZone]"
3. superwerker-RootMail-REDACTED (RootMail) with reason: "The following resource(s) failed to create: [SESReceiveStack]."

After the stack finished with CREATE_FAILED ("The following resource(s) failed to create: [ControlTower, RootMail, Budget].") I decided to run an update. This failed again with same results.

Digging in the logs brings up more insights:
1. RootMail (deployed in eu-west-1 likely due to SES service/feature availability): "An error occurred (InvalidS3Configuration) when calling the CreateReceiptRule operation: Could not publish to bucket superwerker-rootmail-REDACTED-emailbucket-REDACTED. Your bucket's region is currently not supported by Amazon SES."

Cannot find much more at the moment, I assume "LandingZone" fails because of "RootMail" not completing successfully? However, no clue why "Budget" fails.

Thank you for your support!

### Important Factoids

Deployment to eu-central-2, which should be ok since AWS Control Tower and other services are supported in the region.

**Comment by c-a-m-a-c** [comment]
That seems to be the problem as far as RootMail ist concerned: [SES does not support S3 buckets in Opt-in regions as a destination for inbound emails.](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-s3.html)
eu-central-2 is an [opt-in region](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html).

**Comment by peermuellerxw** [comment]
hi @c-a-m-a-c ,
thanks for your bug report. 
Exactly, eu-central-2 is officially not supported as it is not enabled "by default". We updated the documentation accordingly (Actually the documentation PR was ready, but not merged. Sorry for this.): https://github.com/superwerker/superwerker#which-regions-is-superwerker-available-in
As eu-central-2 is an "opt-in" region there are a few caveats and we have decided to not support it officially, although it might be technically possible. Maybe @aperov9 can shed some light on this...

**Comment by aperov9** [comment]
Hey @c-a-m-a-c 

thanks for creating the issue! We are aware of the problem and updated the docs already, we did not merge the PR https://github.com/superwerker/superwerker/pull/449 until now to reflect that we do not support regions that are not enabled by default for now.

We documented the following regarding eu-central-2 so far:

1. Control Tower with "AWS Control Tower failed to set up your landing zone completely: The Region eu-central-2 is not activated for the Security OU accounts. To continue, activate the Region and try again." This means we need to create the accounts first, activate eu-central-2 inside them, and then continue to install Control Tower. 
2. Budget fails with "Template format error: Unrecognized resource types: [AWS::Budgets::Budget]." We assume the Cloudformation resource is for some reason not available in eu-central-2.
3. Rootmail/SES fails with "Could not publish to bucket superwerker-rootmail-12ak2t9js9b6z-emailbucket-l8iji918hbm9. Your bucket's region is currently not supported by Amazon SES." As you stated this is connected with SES not being able to send to regions that are not enabled by default. This one will be the most difficult to solve since we do not want to break the existing superwerker installations when updating that have the s3 bucket in their home region.

For now, as a workaround, we recommend installing superwerker in regions that are enabled by default and adding the non-enabled region as a secondary region inside Control Tower via the superwerker SSM parameters. For customers in Switzerland in particular, we usually set up superwerker in Frankfurt (since it's much cheaper anyway) and add the Zurich region as a secondary.

**Comment by c-a-m-a-c** [comment]
Thank you for the quick replies. Yes, makes sense - I haven't thought about the problem of enabling the region in subsequent accounts, yet, especially tricky when it comes to AWS Control Tower. And I appreciate you stick to your principles! Keep up the good work!

**Comment by aperov9** [comment]
Regarding your second error:

> The update of the CFN stack failed with reason: "Resource handler returned message: "AWS Control Tower detected '2' validation errors:The OU with name Security already exists in AWS Organization, please enter a different name for the OU; The OU with name Sandbox already exists in AWS Organization, please enter a different name for the OU (Service: ControlTower, Status Code: 400, Request ID: REDACTED)" (RequestToken: REDACTED, HandlerErrorCode: InvalidRequest)"

This means you need to clean up your AWS Org Structure & potentially even get rid of the LogArchive & Audit Account altogether. The cleanup is pretty annoying since Control Tower retains a bunch of resources. I would recommend just starting over with a new account if possible and e.g. roll out superwerker in eu-central-1 instead.

**Comment by c-a-m-a-c** [comment]
(this is just a test environment, no worries. Reason why we test 😎.)

**Comment by grolston** [comment]
HI all, I thought I would share this as I have not seen an example out in the public yet. I as well had some issues getting the control-tower.yaml template to deploy back in December 2023 (not sure if related to this bug or not, but it was same code base). I was not sure if the recent API changes to Control Tower caused the issue or not. I recently came back to automating this again and leveraged the new CloudFormation resources. You can see the template here: https://github.com/grolston/control-tower-cloudformation

Updating the template to use these resources would probably reduce the lambdas being deployed. I wasn't ever able to get control tower to successfully deploy with the awsapilib; however, with the newly released CloudFormation resources I have not had to go back to it.

**Comment by peermuellerxw** [comment]
Hi @grolston,
thanks for the link to your cloudformation template. Meanwhile we have also worked on integrating Control Tower using cloudformation and remove the awsapilib code. Feel free to have a look in the [stack](https://github.com/superwerker/superwerker/blob/main/cdk/src/stacks/control-tower.ts).

**Comment by grolston** [comment]
Awesome! I love to see it in the CDK typescript!
